### PR TITLE
BUD-29 View Activity Improvements

### LINKED ISSUE #65: User names in view activities are constrained incorrectly
The cell should probably fill the width of the screen. As you can see, it overlaps with the "remove" button.

img_0330

### LINKED ISSUE #66: Date/location overlap with profile pics on View Activity miniview
Need to constrain this better - perhaps wrap date/location to 2 lines.

img_0337

### LINKED ISSUE #71: The Activity list does not appear to update when navigating away and back to the screen
For example, when the member list of an activity changes, the pictures on the list do not update.

To duplicate, (on the latest branch which includes leaving an activity), go to an activity you're a member of which has 3 or less members. Observe the (possibly) correct number of profile pictures on the activity list, then go to the activity. Leave the activity. You'll be taken back to the activity list, which will still show the activity as having the same users. Since there were 3 or so members, there should be one less picture, but it still has the original pics. See gif for this in action:

leave_activity_bug

I think this is also an issue when you delete an activity. When you delete the activity, it takes you back to the list, but the activity will still be on the list, even though the `onInvalidate` code is called from the data manager class.

cc @lukemeierj @JakeThurman who wrote related code

### PR DESCRIPTION
**Pull request by noahtallen**
This PR should finalize almost everything about View Activity. Here is the list of changes:

- Improve constraints around the board. Resolves #66, fixes #65. Should cut off text at the right points instead of putting them under images.
- Report works. You can tap it, send a report message, and it'll save to the database. _Note, you should not be able to see the report button if you own the activity_
- Fix weird flashing on activity when different things happen. This is because I re-ran the animation code every time anything updated. Now it only runs the animation code when the animation state has changed.
- You can now leave an activity (a confirmation dialogue pops up first) if you are _not_ the owner.
- You can now tap a button and confirm deleting an activity if you are the owner, but it doesn't do anything yet. (next pr)
- The segue to view activity is now a nav controller push instead of show modally. Looks a lot better and allows for swipe back.
- You can now remove a user if you are the owner

### Test:
- Join some activities, leave some activities, remove people from activities.
- Note that everything should happen in real-time. If you're looking at the same activity and two devices, changes to anything about the activity (including removing or adding users) should update nearly instantly.
- Try opening an activity with >4 topics. Then scroll the topics. Make sure there is no flash on the screen.
- Navigate to activities and make sure the back button works, as does swiping back.
- Tap the report button and send a report message. See if it shows up in Firestore.
- Make sure you can't see the report button if you own the activity.
- Make sure you can't see the "remove" button if you do NOT own the activity.
- Make sure long user names are cut off properly before the "remove" button and don't push it off-screen
- Make sure long dates/locations are cutoff before the profile pictures in the mini-description.

**ALSO FIXES #71*

### Screenshots of it working better:
screen shot 2019-02-23 at 6 20 47 pm
screen shot 2019-02-23 at 7 09 06 pm
screen shot 2019-02-23 at 7 17 34 pm

### CODE REVIEW

**Comment by noahtallen** [comment]
Note: working on delete activity.

**Comment by noahtallen** [comment]
I'm sorry for a) putting so much in this PR and b) not testing and c) naming the branch badly. Thankfully, this is basically the last thing to do for view activity, so I'll be working on tests for pretty much the entire rest of the sprint

**Comment by lukemeierj** [comment]
Could the report pop-up be a full text-area like our original design?  I think the hypothetical reports we'd expect would merit more than a line.   

screen shot 2019-02-24 at 10 25 53 pm
image

**Comment by lukemeierj** [comment]
Image wouldn't save in my prev comment:

image

**Comment by lukemeierj** [comment]
According to [iOS design guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/), "Cancel" should always be on the left

> Place buttons where people expect them. In general, buttons people are most likely to tap should be on the right. Cancel buttons should always be on the left.

screen shot 2019-02-24 at 10 25 53 pm

**Review by lukemeierj — CHANGES_REQUESTED** [review]
Other than testing on multiple devices, this all runs great.  Great work!

Be great of you could look into those two things about the report button, otherwise looks sweet!

**Comment by noahtallen** [comment]
I agree - however, it's apparently not possible with alerts in iOS. You can't make the textfield more than one line and I couldn't find a way to do a multi line textview in the alert either   
  

  
  

  
  
>

**Comment by noahtallen** [comment]
True! I guess it adds those in the order defined by the code. I'll switch that for all of them
  

  
  

  
  
>

**Comment by noahtallen** [comment]
I have the cancel button fixed, looking into alternatives for reports. we'll need this for user reporting anyways.

**Comment by noahtallen** [comment]
@lukemeierj I think converting to be a bigger textfield will require re-writing this to be a full-on VC with its own storyboard and whatnot. ([see here](https://stackoverflow.com/questions/16230700/display-uiviewcontroller-as-popup-in-iphone)). We can't extend the current method to be multi-line. Would you be okay deferring that until we get around to reporting users? Then we can tackle the whole thing in the scope of one story, and also make sure to build it in such a way that it's super easy to also use here.

**Comment by lukemeierj** [comment]
Yep, good with deferring it as long as we get it eventually 👍

**Review by lukemeierj — APPROVED** [review]

**Pull request merged**
