### PR TITLE
Bud 102 Favorite Topics from Activities Table

### LINKED ISSUE #63: Date on Activity list should be capitalized
You can do this on any string with `.capitalized`.

img_0331

### PR DESCRIPTION
**Pull request by lukemeierj**
Little star in Activities table that lets you favorite a topic

Also fix annoying constraint problem with Activity cell.

To test:
1. Go to Topics
2. Click a topic, verify the star is blue if you've favorited it, or empty if you haven't
3. Toggle the star
4. Verify that it's toggled on the main topics tab

_NOTE: This also resolves #63_

### CODE REVIEW

**Comment by noahtallen** [comment]
So on first read of the code I feel like it's very tightly coupled - all the VCs seem tightly coupled, and reference each other directly. I also don't super like the pattern of changing the UI of the child from the parent - in my mind, it's better to let the parent give the child the data and then the child can handle its own layout.

I also wonder if it might be a good idea to link changing the user's favorite topics with the redner of the favorited topics. Right now, you kinda manually tell the root VC to change the selected state of a topic manually. That seems weird to me. Why not just favorite the actual topic from the topic view and let the "useUser" updater handle changing the selected state?

I'm on my phone so I didn't really do an in depth reviews or test, those are just my thoughts from looking over the code

**Comment by lukemeierj** [comment]
@noahtallen You raise a fair point, it is tightly coupled and that's wrong. In our final design, TopicsTab will only ever generate the TopicsActivityTable, and the TopicsActivityTable will only ever be the child on the TopicsTab so we don't really gain anything by being more abstract.  I'll look into it, but it mostly means copying code from the parent VC and pasting it in the table, which isn't great either.

**Review by noahtallen — APPROVED** [review]
LGTM! Seems to test well. Up to you if you want to improve the code style ;)

**Comment by noahtallen** [comment]
Yeah copy-pasting code isn't a good idea either. One thing I was thinking is passing a callback down to the child, which might be cleaner than calling the super

**Comment by lukemeierj** [comment]
@noahtallen Mind taking a peek before merge? Thanks for holding me to a higher standard ;)

_Note_: I cancel the listener on deinit.  That's been dangerous in the past, but I triggered changes to my user object (which triggered my update callback) and I didn't run into any problems.

**Comment by noahtallen** [comment]
Yeah, this code does feel better to me ;) And it still works! 👍

I think ideally you wouldn't have that duplication between those two screens, but that's not an easy problem to solve in a clean way. Looks good though :)

**Pull request merged**
