### PR TITLE
Setup auth for the project

### PR DESCRIPTION
**Pull request by JakeThurman**
This is enough of a restructuring I'd like it get in ASAP

Also: So many tests!

### CODE REVIEW

**Comment by JakeThurman** [comment]
@noahtallen 

There's a pod error I'm not sure how to fix. If you get the chance PLEASE HELP, you're my only hope ;0
```
[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In snapshot (Podfile.lock):
    Firebase/Core (= 5.14.0)
  In Podfile:
    Firebase/Core
None of your spec sources contain a spec satisfying the dependencies: `Firebase/Core, Firebase/Core (= 5.14.0)`.
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by noahtallen** [comment]
The build fails because it's trying to run `pod install`. Even if you run that locally, it fails. I'm trying out some stuff - gonna try `pod update` locally, and I might also try to tell travis to not run pod install.

**Review by noahtallen — APPROVED** [review]
The code looks really good! I like how you were able to compartmentalize and test everything really well. One thought - should we add more checking for passwords? Firebase only requires something like 6 characters, but there aren't any restrictions other than that.

**Comment by JakeThurman** [comment]
@noahtallen I'll put in a reminder to ask Wolfe about auth security, but I don't think it's worth any more time right now. The defaults are _okay_.

**Comment by noahtallen** [comment]
Sounds good to me
  

  
  

  
  
>

**Pull request merged**
