### PR TITLE
Topic collection tests

### PR DESCRIPTION
**Pull request by lukemeierj**
This is one of my stories to improve testing for Topics.  I don't know the story ID because I don't have VPN set up on my mac.

To test:
* Make sure the topics collection still works
* Tests still pass

### CODE REVIEW

**Comment by noahtallen** [comment]
@lukemeierj p.s. the build is failing if you weren't aware ;)

**Comment by lukemeierj** [comment]
@noahtallen Yep! Did know.  All set now.

**Comment by lukemeierj** [comment]
The diff isn't 100% covered because I fixed indentation of a class in this PR.

**Review by noahtallen — APPROVED** [review]
Seems to work well 🚀

**Comment by lukemeierj** [comment]
For record, as @noahtallen mentioned to me in Slack, at this point our app does not work.  However, it is related to a bunch of problems with splitting private and public user data, not this PR.

**Pull request merged**
