### PR TITLE
Issue 61

### PR DESCRIPTION
**Pull request by JadaTBK**
- fixes "this month" bug
- more detailed  popups when validating info for creating an activity
- pulls the location data from the first result if not tapped on

### CODE REVIEW

**Review by noahtallen — APPROVED** [review]
Btw to automatically close an issue when we merge the PR, you can do "fix #61" (along with a few other keywords ;))

Also the date looks like it's working well! Thanks for adding that clarified dialogue stuff

Also, if you put in text for a location but don't select any location, it looks like it defaults to using a result anyways. Is that expected? I typed in something like "asdfghth" and didn't see any results show up immediately, but it still selected a default one

**Comment by lukemeierj** [comment]
@noahtallen @gyurisic Is this what you mean by

> * pulls the location data from the first result if not tapped on

Either way, I think it's better to give a useful alert when the user entered a location that doesn't work or doesn't have results.  Users should know what's happening.

**Comment by lukemeierj** [comment]
Is it possible to have it highlight the cell, not the text field?

I think it should be possible.  It should look kind of like when you focus into an input field (on web), but red instead of blue.

If it isn't possible, I'm not sure we should add the border.
screen shot 2019-02-25 at 6 26 48 pm

**Comment by JadaTBK** [comment]
I def spent way too long on trying to get the cell thing working but i got it after trying again for 2 minutes after seeing this LOL; the latest commit does the border around the cell

**Pull request merged**
